services:
  admin:
    build:
      context: ../../../
      dockerfile: tamanomi-admin/infrastructure/docker/Dockerfile
      target: dev
      args:
        - GITHUB_TOKEN=${GITHUB_TOKEN}
    ports:
      - "3001:3000"
    env_file:
      - ../../frontend/.env
    environment:
      - PORT=3000
    volumes:
      - ../../frontend:/app
      - admin_node_modules:/app/node_modules
      - /app/.next
    networks:
      - tamanomi-network
    external_links:
      - tamanomi-api_api-1

volumes:
  admin_node_modules:

networks:
  tamanomi-network:
    external: true
    name: tamanomi-network