services:
  admin:
    build:
      context: ../../../
      dockerfile: tamanomi-admin/infrastructure/docker/Dockerfile
      target: dev
    ports:
      - "3001:3000"
    env_file:
      - ../../../tamanomi-admin/.env
    environment:
      - NODE_ENV=development
      - API_BASE_URL=http://tamanomi-api-api-1:3002/api/v1
    volumes:
      - ../../../tamanomi-admin/frontend:/app
      - /app/node_modules
      - /app/.next
      - ../../../tamanomi-schemas:/app/tamanomi-schemas
    networks:
      - tamanomi-network
    external_links:
      - tamanomi-api_api-1

networks:
  tamanomi-network:
    external: true
    name: tamanomi-api_tamanomi-network